FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/web1/package*.json ./apps/web1/
RUN npm install
COPY . .
RUN cd apps/web1 && npm run build
EXPOSE 3000
CMD ["sh", "-c", "npm run start --workspace=apps/web1"]
