import fs from 'fs/promises';
import path from 'path';
import { prisma } from './db';
import { getSettings, saveSetting } from './settings-db';
import { executeGitAction } from './git-sync-service';

export interface KbGenerateResult {
  status: 'success' | 'error';
  date: string;
  cases: number;
  outputDir: string;
  log: string;
  error?: string;
}

function yamlString(value: string | null | undefined): string {
  const text = (value || '').replace(/\r\n/g, '\n').trim();
  if (!text) return '""';
  if (!text.includes('\n') && text.length < 100) return JSON.stringify(text);
  return `|\n${text.split('\n').map((line) => `  ${line}`).join('\n')}`;
}

function dateRange(date: string) {
  const start = new Date(`${date}T00:00:00.000Z`);
  const end = new Date(start);
  end.setUTCDate(end.getUTCDate() + 1);
  return { start, end };
}

export async function autoGenerateDailyKB(date = new Date().toISOString().split('T')[0], push = true): Promise<KbGenerateResult> {
  const settings = await getSettings();
  const repoPath = settings['knowledge.repoPath'] || settings['git.localPath'] || '/root/openstack-support';
  const outputDir = path.join(repoPath, 'auto-generated', date);
  let log = `[${new Date().toISOString()}] Starting KB auto generation for ${date}\n`;

  await saveSetting('kb-auto.running', 'true');
  await saveSetting('kb-auto.lastError', '');

  try {
    const { start, end } = dateRange(date);
    const cases = await prisma.case.findMany({
      where: {
        status: 'closed',
        closedAt: { gte: start, lt: end },
      },
      include: { messages: { orderBy: { createdAt: 'asc' } } },
      orderBy: { closedAt: 'asc' },
    });

    await fs.mkdir(path.join(outputDir, 'cases'), { recursive: true });

    for (const item of cases) {
      const transcript = item.messages.map((message) => `${message.role}: ${message.content}`).join('\n');
      const content = [
        `case_id: ${JSON.stringify(item.caseId)}`,
        `date: ${JSON.stringify(date)}`,
        `role: ${JSON.stringify(item.page)}`,
        `status: ${JSON.stringify(item.status)}`,
        `summary: ${yamlString(item.summary || item.preview)}`,
        `resolution: ${yamlString(item.detail)}`,
        `root_cause: ""`,
        `kb_suggestion: "Review this case for manual curation."`,
        `tags:`,
        `  - auto-generated`,
        `  - ${item.page.toLowerCase()}`,
        `messages_count: ${item.messages.length}`,
        `user: ${JSON.stringify(item.username)}`,
        `transcript: ${yamlString(transcript)}`,
        '',
      ].join('\n');
      await fs.writeFile(path.join(outputDir, 'cases', `${item.caseId}-${item.page.toLowerCase()}.yaml`), content, 'utf8');
    }

    const digest = [
      `date: ${JSON.stringify(date)}`,
      `total_cases: ${cases.length}`,
      `by_role:`,
      `  noc: ${cases.filter((item) => item.page === 'NOC').length}`,
      `  operation: ${cases.filter((item) => item.page === 'Operation').length}`,
      `case_ids:`,
      ...cases.map((item) => `  - ${JSON.stringify(item.caseId)}`),
      '',
    ].join('\n');
    await fs.writeFile(path.join(outputDir, 'daily-digest.yaml'), digest, 'utf8');

    const stats = [
      `date: ${JSON.stringify(date)}`,
      `cases:`,
      `  total: ${cases.length}`,
      `  noc: ${cases.filter((item) => item.page === 'NOC').length}`,
      `  operation: ${cases.filter((item) => item.page === 'Operation').length}`,
      `messages: ${cases.reduce((sum, item) => sum + item.messages.length, 0)}`,
      '',
    ].join('\n');
    await fs.writeFile(path.join(outputDir, 'stats.yaml'), stats, 'utf8');

    log += `Wrote ${cases.length} cases to ${outputDir}\n`;

    if (push) {
      const pushStatus = await executeGitAction('push_auto_generated', 'kb-auto', { date });
      log += `Git push status: ${pushStatus.status}\n${pushStatus.lastLog}\n`;
    }

    const result: KbGenerateResult = { status: 'success', date, cases: cases.length, outputDir, log };
    await saveSetting('kb-auto.lastRunAt', new Date().toISOString());
    await saveSetting('kb-auto.lastResult', JSON.stringify(result));
    await saveSetting('kb-auto.lastLog', log.slice(-5000));
    return result;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'KB generation failed';
    log += `[ERROR] ${message}\n`;
    const result: KbGenerateResult = { status: 'error', date, cases: 0, outputDir, log, error: message };
    await saveSetting('kb-auto.lastError', message);
    await saveSetting('kb-auto.lastResult', JSON.stringify(result));
    await saveSetting('kb-auto.lastLog', log.slice(-5000));
    return result;
  } finally {
    await saveSetting('kb-auto.running', 'false');
  }
}
