import { autoGenerateDailyKB } from './auto-kb-generator';
import { getSettings, saveSetting } from './settings-db';

let interval: NodeJS.Timeout | null = null;

export function startScheduler() {
  if (interval) return;
  interval = setInterval(tickScheduler, 60_000);
}

export function stopScheduler() {
  if (interval) clearInterval(interval);
  interval = null;
}

async function tickScheduler() {
  const settings = await getSettings();
  if (settings['kb-auto.enabled'] !== 'true') return;
  if (settings['kb-auto.running'] === 'true') return;

  const scheduleTime = settings['kb-auto.scheduleTime'] || '23:59';
  const now = new Date();
  const currentTime = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  if (currentTime !== scheduleTime) return;

  const today = now.toISOString().split('T')[0];
  if (settings['kb-auto.lastRunAt']?.startsWith(today)) return;

  const result = await autoGenerateDailyKB(today, true);
  if (result.status === 'error') {
    await saveSetting('kb-auto.lastError', result.error || 'Unknown scheduler error');
  }
}
