import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { autoGenerateDailyKB } from '@/lib/auto-kb-generator';
import { saveSetting } from '@/lib/settings-db';
import { apiErrorResponse } from '@/lib/api-error';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    await requireAuth(['admin']);
    const body = await request.json().catch(() => ({}));
    if (typeof body.enabled === 'boolean') {
      await saveSetting('kb-auto.enabled', body.enabled ? 'true' : 'false');
    }
    if (typeof body.scheduleTime === 'string') {
      await saveSetting('kb-auto.scheduleTime', body.scheduleTime);
    }

    if (body.action === 'save_settings') {
      return NextResponse.json({ success: true });
    }

    const date = typeof body.date === 'string' ? body.date : undefined;
    const push = body.push !== false;
    const result = await autoGenerateDailyKB(date, push);
    return NextResponse.json(result, { status: result.status === 'success' ? 200 : 500 });
  } catch (error) {
    return apiErrorResponse(error, '[KB Auto Generate API]');
  }
}
